# Generated by Django 2.2.5 on 2019-10-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=110)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Habitacion',
                'verbose_name_plural': 'Tipos de Habitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('imagen', models.URLField(default='https://www.info-computer.com/blog/wp-content/uploads/2018/04/fotoinicio.jpg', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('tipoUsuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoUsuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diaInicio', models.DateField()),
                ('diaFin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitaciones', models.ManyToManyField(to='api.Habitacion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='img/habitaciones/no-img.jpg', upload_to='img/habitaciones/')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Habitacion')),
            ],
            options={
                'verbose_name': 'Imagen Habitacion',
                'verbose_name_plural': 'Imagenes de Habitacion',
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipoHabitacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoHabitacion'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitaciones', models.ManyToManyField(to='api.Habitacion')),
            ],
            options={
                'verbose_name': 'Comodidad',
                'verbose_name_plural': 'Comodidades',
            },
        ),
    ]
