# Generated by Django 2.2.5 on 2019-11-02 02:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('foto_perfil', models.URLField(default='https://www.info-computer.com/blog/wp-content/uploads/2018/04/fotoinicio.jpg', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=110)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='HabitacionAsignada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Habitacion')),
            ],
            options={
                'verbose_name': 'Habitacion Asignada',
                'verbose_name_plural': 'Habitaciones Asignadas',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Habitacion',
                'verbose_name_plural': 'Tipos de Habitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitaciones', models.ManyToManyField(through='api.HabitacionAsignada', to='api.Habitacion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsable', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.URLField(default='https://www.parkpiolets.com/content/imgsxml/galerias/panel_habitaciones/6/des-0016-pioletspark-doblepremium320.jpg', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Habitacion')),
            ],
            options={
                'verbose_name': 'Imagen Habitacion',
                'verbose_name_plural': 'Imagenes de Habitacion',
            },
        ),
        migrations.AddField(
            model_name='habitacionasignada',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Reserva'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipoHabitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoHabitacion'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Reserva')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Comodidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=110)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('habitaciones', models.ManyToManyField(to='api.Habitacion')),
            ],
            options={
                'verbose_name': 'Comodidad',
                'verbose_name_plural': 'Comodidades',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
