# Generated by Django 2.2.5 on 2019-11-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.TipoUsuario'),
        ),
    ]
