# Generated by Django 2.2.5 on 2019-10-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191026_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='foto_perfil',
        ),
    ]
