# Generated by Django 2.2.5 on 2019-10-27 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='foto_perfil',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
