# Generated by Django 2.2.5 on 2019-11-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='reservada',
            field=models.BooleanField(default=False),
        ),
    ]
