# Generated by Django 2.2.5 on 2019-10-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191027_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='foto_perfil',
        ),
    ]
