# Generated by Django 2.2.5 on 2019-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_habitacion_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacionasignada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
