# Generated by Django 2.2.5 on 2019-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191102_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitacionAsignada',
            new_name='HabitacionReservada',
        ),
    ]
