# Generated by Django 2.2.5 on 2019-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191111_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(default=123),
        ),
    ]
