# Generated by Django 2.2.5 on 2019-11-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191114_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
